### ISSUE TITLE
Invalid reference on bot.js line 51

### ISSUE THREAD

**Issue by WangNianyi2001** [MageOChicken/MageAI-5D#3]
`evaluation.evalMove` is an empty array at the first place, therefore accessing its last element would get you an `undefined`.
![](https://user-images.githubusercontent.com/19430435/132936868-fe88316f-6c39-4eec-a931-50a3fbfccf9f.png)

**Comment by MageOfficial** [comment]
This issue should hopefully be fixed now. Before i was working off a different version of 5d-chess-js which caused the evaluations to fail.
